Type changed to float
Traceback (most recent call last):
  File "ICHOR.py", line 4696, in <module>
    _call_external_function(*_call_external_function_args)
  File "ICHOR.py", line 4557, in calculate_errors
    points = models.expected_improvement(sample_pool)
  File "ICHOR.py", line 3418, in expected_improvement
    self.write_data(points_to_add, points)
  File "ICHOR.py", line 3411, in write_data
    json.dump(data, f)
  File "/opt/gridware/depots/8e896c5a/el7/pkg/apps/anaconda3/5.2.0/bin/lib/python3.6/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/opt/gridware/depots/8e896c5a/el7/pkg/apps/anaconda3/5.2.0/bin/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/gridware/depots/8e896c5a/el7/pkg/apps/anaconda3/5.2.0/bin/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/opt/gridware/depots/8e896c5a/el7/pkg/apps/anaconda3/5.2.0/bin/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/opt/gridware/depots/8e896c5a/el7/pkg/apps/anaconda3/5.2.0/bin/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/opt/gridware/depots/8e896c5a/el7/pkg/apps/anaconda3/5.2.0/bin/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'int64' is not JSON serializable